// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

public final class Direct {
    public static final short Given = -1;
    public static final short None = 0;
    public static final short Paid = 1;
    public static final String[] names = {"Given", "None", "Paid",};

    private Direct() {
    }

    public static String name(int e) {
        return names[e - Given];
    }
}

