// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class FALevel extends Struct {
    public static int createFALevel(FlatBufferBuilder builder, double qty, double price) {
        builder.prep(8, 16);
        builder.putDouble(price);
        builder.putDouble(qty);
        return builder.offset();
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public FALevel __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public double qty() {
        return bb.getDouble(bb_pos + 0);
    }

    public double price() {
        return bb.getDouble(bb_pos + 8);
    }
}

