// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

public final class InstrType {
  private InstrType() { }
  public static final short None = 0;
  public static final short SpotFwd = 1;
  public static final short Future = 2;
  public static final short CFD = 3;
  public static final short Swap = 4;

  public static final String[] names = { "None", "SpotFwd", "Future", "CFD", "Swap", };

  public static String name(int e) { return names[e]; }
}

