// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

public final class LiqInd {
  private LiqInd() { }
  public static final short None = 0;
  public static final short Maker = 1;
  public static final short Taker = 2;

  public static final String[] names = { "None", "Maker", "Taker", };

  public static String name(int e) { return names[e]; }
}

