// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class MDEntry extends Struct {
    public static int createMDEntry(FlatBufferBuilder builder, int level, int venueId, double qty, double price) {
        builder.prep(8, 24);
        builder.putDouble(price);
        builder.putDouble(qty);
        builder.putInt(venueId);
        builder.putInt(level);
        return builder.offset();
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public MDEntry __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public int level() {
        return bb.getInt(bb_pos + 0);
    }

    public int venueId() {
        return bb.getInt(bb_pos + 4);
    }

    public double qty() {
        return bb.getDouble(bb_pos + 8);
    }

    public double price() {
        return bb.getDouble(bb_pos + 16);
    }
}

