// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Struct;

import java.nio.ByteBuffer;

@SuppressWarnings("unused")
public final class MDLevel extends Struct {
    public static int createMDLevel(FlatBufferBuilder builder, double qty, double price, double avgPrice, int count) {
        builder.prep(8, 32);
        builder.pad(4);
        builder.putInt(count);
        builder.putDouble(avgPrice);
        builder.putDouble(price);
        builder.putDouble(qty);
        return builder.offset();
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
    }

    public MDLevel __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public double qty() {
        return bb.getDouble(bb_pos + 0);
    }

    public double price() {
        return bb.getDouble(bb_pos + 8);
    }

    public double avgPrice() {
        return bb.getDouble(bb_pos + 16);
    }

    public int count() {
        return bb.getInt(bb_pos + 24);
    }
}

