// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Message extends Table {
    public static Message getRootAsMessage(ByteBuffer _bb) {
        return getRootAsMessage(_bb, new Message());
    }

    public static Message getRootAsMessage(ByteBuffer _bb, Message obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static boolean MessageBufferHasIdentifier(ByteBuffer _bb) {
        return __has_identifier(_bb, "RMKS");
    }

    public static int createMessage(FlatBufferBuilder builder,
                                    long tts,
                                    long rts,
                                    int sid,
                                    int options,
                                    int padding,
                                    byte body_type,
                                    int bodyOffset) {
        builder.startObject(7);
        Message.addRts(builder, rts);
        Message.addTts(builder, tts);
        Message.addBody(builder, bodyOffset);
        Message.addSid(builder, sid);
        Message.addPadding(builder, padding);
        Message.addOptions(builder, options);
        Message.addBodyType(builder, body_type);
        return Message.endMessage(builder);
    }

    public static void startMessage(FlatBufferBuilder builder) {
        builder.startObject(7);
    }

    public static void addTts(FlatBufferBuilder builder, long tts) {
        builder.addLong(0, tts, 0L);
    }

    public static void addRts(FlatBufferBuilder builder, long rts) {
        builder.addLong(1, rts, 0L);
    }

    public static void addSid(FlatBufferBuilder builder, int sid) {
        builder.addInt(2, sid, 0);
    }

    public static void addOptions(FlatBufferBuilder builder, int options) {
        builder.addShort(3, (short) options, (short) 0);
    }

    public static void addPadding(FlatBufferBuilder builder, int padding) {
        builder.addShort(4, (short) padding, (short) 0);
    }

    public static void addBodyType(FlatBufferBuilder builder, byte bodyType) {
        builder.addByte(5, bodyType, 0);
    }

    public static void addBody(FlatBufferBuilder builder, int bodyOffset) {
        builder.addOffset(6, bodyOffset, 0);
    }

    public static int endMessage(FlatBufferBuilder builder) {
        int o = builder.endObject();
        return o;
    }

    public static void finishMessageBuffer(FlatBufferBuilder builder, int offset) {
        builder.finish(offset, "RMKS");
    }

    public static void finishSizePrefixedMessageBuffer(FlatBufferBuilder builder, int offset) {
        builder.finishSizePrefixed(offset, "RMKS");
    }

    public void __init(int _i, ByteBuffer _bb) {
        bb_pos = _i;
        bb = _bb;
        vtable_start = bb_pos - bb.getInt(bb_pos);
        vtable_size = bb.getShort(vtable_start);
    }

    public Message __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public long tts() {
        int o = __offset(4);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public long rts() {
        int o = __offset(6);
        return o != 0 ? bb.getLong(o + bb_pos) : 0L;
    }

    public int sid() {
        int o = __offset(8);
        return o != 0 ? bb.getInt(o + bb_pos) : 0;
    }

    public int options() {
        int o = __offset(10);
        return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0;
    }

    public int padding() {
        int o = __offset(12);
        return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0;
    }

    public byte bodyType() {
        int o = __offset(14);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public Table body(Table obj) {
        int o = __offset(16);
        return o != 0 ? __union(obj, o) : null;
    }
}

