// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

public final class SubReqType {
    public static final short Snapshot = 0;
    public static final short Subscribe = 1;
    public static final short Unsubscribe = 2;
    public static final String[] names = {"Snapshot", "Subscribe", "Unsubscribe",};

    private SubReqType() {
    }

    public static String name(int e) {
        return names[e];
    }
}

