// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

public final class VenueFlag {
  private VenueFlag() { }
  public static final short OrderBook = 1;
  public static final short FullAmount = 2;
  public static final short Indicative = 4;

  public static final String[] names = { "OrderBook", "FullAmount", "", "Indicative", };

  public static String name(int e) { return names[e - OrderBook]; }
}

