// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Venue extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static Venue getRootAsVenue(ByteBuffer _bb) { return getRootAsVenue(_bb, new Venue()); }
  public static Venue getRootAsVenue(ByteBuffer _bb, Venue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Venue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int id() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String symbol() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer symbolAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer symbolInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public String display() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer displayAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer displayInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }
  public int flags() { int o = __offset(10); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }

  public static int createVenue(FlatBufferBuilder builder,
      int id,
      int symbolOffset,
      int displayOffset,
      int flags) {
    builder.startTable(4);
    Venue.addDisplay(builder, displayOffset);
    Venue.addSymbol(builder, symbolOffset);
    Venue.addId(builder, id);
    Venue.addFlags(builder, flags);
    return Venue.endVenue(builder);
  }

  public static void startVenue(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addId(FlatBufferBuilder builder, int id) { builder.addInt(0, id, 0); }
  public static void addSymbol(FlatBufferBuilder builder, int symbolOffset) { builder.addOffset(1, symbolOffset, 0); }
  public static void addDisplay(FlatBufferBuilder builder, int displayOffset) { builder.addOffset(2, displayOffset, 0); }
  public static void addFlags(FlatBufferBuilder builder, int flags) { builder.addShort(3, (short)flags, (short)0); }
  public static int endVenue(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 6);  // symbol
    builder.required(o, 8);  // display
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Venue get(int j) { return get(new Venue(), j); }
    public Venue get(Venue obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

