// automatically generated by the FlatBuffers compiler, do not modify

package com.reactivemarkets.encoding.fbs;

public final class VenueFlag {
    public static final short OrderBook = 1;
    public static final short FullAmount = 2;
    public static final String[] names = {"OrderBook", "FullAmount",};

    private VenueFlag() {
    }

    public static String name(int e) {
        return names[e - OrderBook];
    }
}

